version: '3.8'

services:
  backend:
    env_file: .env
    build: .
    ports:
      - $PORT:$PORT
    depends_on:
      - redis
      - postgres
      - chroma_db

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_USER: $POSTGRESDB_USER
      POSTGRES_PASSWORD: $POSTGRESDB_PASSWORD
      POSTGRES_DB: $POSTGRESDB_NAME
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data

  chroma_db:
    image: chromadb/chroma:latest
    volumes:
      - chroma_data:/var/lib/chroma/data

volumes: 
  postgres_data:
  redis_data:
  chroma_data: